name: 'WissKI Sweet'
description: 'WissKI environment with default data model.'
type: 'Site'

recipes:
  - wisski_grain_yeast_water

install:
  - geofield
  - leaflet

config:
  #strict: false # this is not implemented in D11 right now
  import:
    geofield: "*"
    leaflet: "*"
