name: 'WissKI Sweet'
description: 'WissKI environment with default data model.'
type: 'Site'

recipes:
  - wisski_grain_yeast_water

install:
  - conditional_fields
  - field_group
  - geofield
  - leaflet
  - viewfield

config:
  strict: false
  import:
    conditional_fields: "*"
    field_group: "*"
    geofield: "*"
    leaflet: "*"
    viewfield: "*"
