wisski_use_only_main_bundles: 1
wisski_use_views_for_navigate: 1
wisski_enableAutocompleteEverywhere: 1
wisski_max_entities_per_page: '10'
wisski_preview_image_max_width_pixel: '100'
wisski_preview_image_max_height_pixel: '100'
wisski_titles_master_fallback: '"-!- ".t("invalid title")." -!-"'
wisski_standard_field_mapping: value
wisski_throw_exceptions: 'TRUE'
wisski_core_lod_uri_templates: "array('' => $base_url . '/inst/%{bundle}/%{hash}')"
wisski_default_title_pattern:
  p0:
    optional: '1'
    cardinality: '1'
    delimiter: ', '
    parents: ''
    weight: '0'
    type: path
    name: bundle_label
    id: p0
    label: "The bundle's label"
    remove_op: remove
  t1:
    label: ' '
    optional: ''
    cardinality: ''
    delimiter: ''
    weight: '0'
    type: text
    name: textt1
    id: t1
    remove_op: remove
    parents:
      p2: true
  p2:
    optional: '1'
    cardinality: '1'
    delimiter: ', '
    parents: ''
    weight: '0'
    type: path
    name: eid
    id: p2
    label: "Entity's Drupal ID"
    remove_op: remove
  max_id: 2
wisski_use_additionally_sub_bundles: 1
wisski_default_columns_per_page: ''
preview_image_adapters: {  }
enable_published_status_everwhere: 0
use_get_canonical: 0
